from opencompass.models import HuggingFaceCausalLM

models = [
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_096000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_096000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_192000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_192000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_288000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_288000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_384000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_384000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_480000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_480000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_576000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_576000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_672000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_672000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'exp2.1/1283.46B',
    #     'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb512_gas2/exp2.1/hf_ckpt/1283.46B',
    #     'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_amber_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'LLM360/Amber',
    #     'path': 'LLM360/Amber',
    #     'tokenizer_path': 'LLM360/Amber',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '301.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/299.98B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '129.98B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.4/hf_ckpt/129.98B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '99.98B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/99.98B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '89.98B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/89.98B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '79.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/79.99B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '69.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/69.99B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '49.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/49.99B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '199.96B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/199.96B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '149.97B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/149.97B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '39.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/39.99B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '29.99B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/29.99B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '20.00B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/20.00B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': '10.00B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/10.00B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/449.92B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/449.92B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/499.91B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/499.91B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },  
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/549.90B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/549.90B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },     
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/599.89B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/599.89B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },     
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/649.88B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/649.88B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },     
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/699.87B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/699.87B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },   
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/749.86B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/749.86B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },    
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/799.85B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/799.85B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },  
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/849.84B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/849.84B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },   
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/899.84B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/899.84B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # }, 
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/949.83B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/899.84B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },  
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/999.82B',
    #     'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/899.84B',
    #     'tokenizer_path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 4,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },     
    {
        'type': 'HuggingFaceCausalLM',
        'abbr': 'exp5.1/70B',
        'path': '/workspace/megatron/checkpoints/hkg_7b_nl_tp2_pp1_mb1_gb1024_gas8/exp5.1/megatron_legacy_hf_ckpt/iter_0016688',
        'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_baichuan_hf',
        'tokenizer_kwargs': {
            'padding_side': 'left',
            'truncation_side': 'left',
            'use_fast': False,
            'trust_remote_code': True,
        },
        'max_out_len': 100,
        'max_seq_len': 4096,
        'batch_size': 16,
        'model_kwargs': {
            'device_map': 'auto', 
            'trust_remote_code': True,
        },
        'batch_padding': False,
        'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    },
]

