from opencompass.models import HuggingFaceCausalLM

models = [
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_096000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_096000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_192000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_192000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_288000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_288000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_384000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_384000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_480000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_480000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_576000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_576000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },{
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'slimpajama/hf_672000',
    #     'path': '/workspace/code/hf_ckpt/slimpajama/hf_672000',
    #     'tokenizer_path': 'baichuan-inc/Baichuan2-7B-Base',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 2048,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.2/499.96B',
    #     'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1024_gas2/pt1.2/hf_ckpt/499.96B',
    #     'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.4/79.99B',
    #     'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.4/hf_ckpt/79.99B',
    #     'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'pt1.5/49.99B',
    #     'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/49.99B',
    #     'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_baichuan_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    {
        'type': 'HuggingFaceCausalLM',
        'abbr': 'pt1.5/99.98B',
        'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb1280_gas2/pt1.5/hf_ckpt/99.98B',
        'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_baichuan_hf',
        'tokenizer_kwargs': {
            'padding_side': 'left',
            'truncation_side': 'left',
            'use_fast': False,
            'trust_remote_code': True,
        },
        'max_out_len': 100,
        'max_seq_len': 4096,
        'batch_size': 16,
        'model_kwargs': {
            'device_map': 'auto', 
            'trust_remote_code': True,
        },
        'batch_padding': False,
        'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'LLM360/Amber',
    #     'path': 'LLM360/Amber',
    #     'tokenizer_path': 'LLM360/Amber',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
    # {
    #     'type': 'HuggingFaceCausalLM',
    #     'abbr': 'exp2.1/1283.46B_debug_convert_1',
    #     'path': '/workspace/code/opencompass/checkpoints/hkg_7b_nl_tp1_pp1_mb1_gb512_gas2/exp2.1/hf_ckpt/debug/iter_0612000',
    #     'tokenizer_path': '/workspace/code/Megatron-LM/hkgai/hf/hkg_amber_hf',
    #     'tokenizer_kwargs': {
    #         'padding_side': 'left',
    #         'truncation_side': 'left',
    #         'use_fast': False,
    #         'trust_remote_code': True,
    #     },
    #     'max_out_len': 100,
    #     'max_seq_len': 4096,
    #     'batch_size': 16,
    #     'model_kwargs': {
    #         'device_map': 'auto', 
    #         'trust_remote_code': True,
    #     },
    #     'batch_padding': False,
    #     'run_cfg': {'num_gpus': 1, 'num_procs': 1},
    # },
]

